const obras = [
  {
    nome: "Obra 1",
    cliente: "Cliente 1",
    dataInicio: "01/01/2023",
    descricao: "Descrição da Obra 1",
    numeroContrato: "Contrato 1",
  },
  {
    nome: "Obra 2",
    cliente: "Cliente 2",
    dataInicio: "02/01/2023",
    descricao: "Descrição da Obra 2",
    numeroContrato: "Contrato 2",
  },
  {
    nome: "Obra 3",
    cliente: "Cliente 3",
    dataInicio: "03/01/2023",
    descricao: "Descrição da Obra 3",
    numeroContrato: "Contrato 3",
  },
  {
    nome: "Obra 4",
    cliente: "Cliente 4",
    dataInicio: "04/01/2023",
    descricao: "Descrição da Obra 4",
    numeroContrato: "Contrato 4",
  },
  {
    nome: "Obra 5",
    cliente: "Cliente 5",
    dataInicio: "05/01/2023",
    descricao: "Descrição da Obra 5",
    numeroContrato: "Contrato 5",
  },
  {
    nome: "Obra 6",
    cliente: "Cliente 6",
    dataInicio: "06/01/2023",
    descricao: "Descrição da Obra 6",
    numeroContrato: "Contrato 6",
  },
  {
    nome: "Obra 7",
    cliente: "Cliente 7",
    dataInicio: "07/01/2023",
    descricao: "Descrição da Obra 7",
    numeroContrato: "Contrato 7",
  },
  {
    nome: "Obra 8",
    cliente: "Cliente 8",
    dataInicio: "08/01/2023",
    descricao: "Descrição da Obra 8",
    numeroContrato: "Contrato 8",
  },
  {
    nome: "Obra 9",
    cliente: "Cliente 9",
    dataInicio: "09/01/2023",
    descricao: "Descrição da Obra 9",
    numeroContrato: "Contrato 9",
  },
  {
    nome: "Obra 10",
    cliente: "Cliente 10",
    dataInicio: "10/01/2023",
    descricao: "Descrição da Obra 10",
    numeroContrato: "Contrato 10",
  },
  {
    nome: "Obra 11",
    cliente: "Cliente 11",
    dataInicio: "11/01/2023",
    descricao: "Descrição da Obra 11",
    numeroContrato: "Contrato 11",
  },
  {
    nome: "Obra 12",
    cliente: "Cliente 12",
    dataInicio: "12/01/2023",
    descricao: "Descrição da Obra 12",
    numeroContrato: "Contrato 12",
  },
  {
    nome: "Obra 13",
    cliente: "Cliente 13",
    dataInicio: "13/01/2023",
    descricao: "Descrição da Obra 13",
    numeroContrato: "Contrato 13",
  },
  {
    nome: "Obra 14",
    cliente: "Cliente 14",
    dataInicio: "14/01/2023",
    descricao: "Descrição da Obra 14",
    numeroContrato: "Contrato 14",
  },
  {
    nome: "Obra 15",
    cliente: "Cliente 15",
    dataInicio: "15/01/2023",
    descricao: "Descrição da Obra 15",
    numeroContrato: "Contrato 15",
  },
  ];

export default obras;

