const ListaEquipamentos = [
  {
    nome: "Bitorneira",
    identificador: "Bitorneira 1",
    peso: "10kg",
    status: "Em uso",
    obra: "Obra 1",
    dataCadastro: "2021-08-01",
    dataAlocação: "2021-08-01",
    responsavel: "João",
  },
  {
    nome: "Escavadeira",
    identificador: "Escavadeira 1",
    peso: "5000kg",
    status: "Em uso",
    obra: "Obra 2",
    dataCadastro: "2021-08-02",
    dataAlocação: "2021-08-02",
    responsavel: "Maria",
  },
  {
    nome: "Betoneira",
    identificador: "Betoneira 1",
    peso: "2000kg",
    status: "Em uso",
    obra: "Obra 3",
    dataCadastro: "2021-08-03",
    dataAlocação: "2021-08-03",
    responsavel: "Pedro",
  },
  {
    nome: "Guindaste",
    identificador: "Guindaste 1",
    peso: "10000kg",
    status: "Em uso",
    obra: "Obra 4",
    dataCadastro: "2021-08-04",
    dataAlocação: "2021-08-04",
    responsavel: "Lucas",
  },
  {
    nome: "Retroescavadeira",
    identificador: "Retroescavadeira 1",
    peso: "7000kg",
    status: "Em uso",
    obra: "Obra 5",
    dataCadastro: "2021-08-05",
    dataAlocação: "2021-08-05",
    responsavel: "Ana",
  },
  {
    nome: "Empilhadeira",
    identificador: "Empilhadeira 1",
    peso: "3000kg",
    status: "Em uso",
    obra: "Obra 6",
    dataCadastro: "2021-08-06",
    dataAlocação: "2021-08-06",
    responsavel: "Carlos",
  },
  {
    nome: "Trator",
    identificador: "Trator 1",
    peso: "6000kg",
    status: "Em uso",
    obra: "Obra 7",
    dataCadastro: "2021-08-07",
    dataAlocação: "2021-08-07",
    responsavel: "Mariana",
  },
  {
    nome: "Caminhão",
    identificador: "Caminhão 1",
    peso: "8000kg",
    status: "Em uso",
    obra: "Obra 8",
    dataCadastro: "2021-08-08",
    dataAlocação: "2021-08-08",
    responsavel: "Gustavo",
  },
  {
    nome: "Pá Carregadeira",
    identificador: "Pá Carregadeira 1",
    peso: "9000kg",
    status: "Em uso",
    obra: "Obra 9",
    dataCadastro: "2021-08-09",
    dataAlocação: "2021-08-09",
    responsavel: "Laura",
  },
  {
    nome: "Motoniveladora",
    identificador: "Motoniveladora 1",
    peso: "12000kg",
    status: "Em uso",
    obra: "Obra 10",
    dataCadastro: "2021-08-10",
    dataAlocação: "2021-08-10",
    responsavel: "Rafael",
  },
  {
    nome: "Compactador",
    identificador: "Compactador 1",
    peso: "4000kg",
    status: "Em uso",
    obra: "Obra 11",
    dataCadastro: "2021-08-11",
    dataAlocação: "2021-08-11",
    responsavel: "Isabela",
  },
];

export default ListaEquipamentos;
