const funcionarios = [
    {
        nome: "Funcionário 1",
        cpf: "111.111.111-11",
        sexo: "Masculino",
        cargo: "Engenheiro",
        email: "funcionario1@example.com",
        telefone: "(11) 1111-1111",
        tipo: "Efetivo",
        dataContratacao: "2020-01-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 2",
        cpf: "222.222.222-22",
        sexo: "Feminino",
        cargo: "Arquiteta",
        email: "funcionario2@example.com",
        telefone: "(22) 2222-2222",
        tipo: "Efetivo",
        dataContratacao: "2020-02-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 3",
        cpf: "333.333.333-33",
        sexo: "Masculino",
        cargo: "Pedreiro",
        email: "funcionario3@example.com",
        telefone: "(33) 3333-3333",
        tipo: "Terceirizado",
        status: "Em atividade",
    },
    {
        nome: "Funcionário 4",
        cpf: "444.444.444-44",
        sexo: "Feminino",
        cargo: "Mestre de Obras",
        email: "funcionario4@example.com",
        telefone: "(44) 4444-4444",
        tipo: "Efetivo",
        dataContratacao: "2020-04-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 5",
        cpf: "555.555.555-55",
        sexo: "Masculino",
        cargo: "Eletricista",
        email: "funcionario5@example.com",
        telefone: "(55) 5555-5555",
        tipo: "Terceirizado",
        status: "Inativo",
    },
    {
        nome: "Funcionário 6",
        cpf: "666.666.666-66",
        sexo: "Feminino",
        cargo: "Encanadora",
        email: "funcionario6@example.com",
        telefone: "(66) 6666-6666",
        tipo: "Efetivo",
        dataContratacao: "2020-06-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 7",
        cpf: "777.777.777-77",
        sexo: "Masculino",
        cargo: "Pintor",
        email: "funcionario7@example.com",
        telefone: "(77) 7777-7777",
        tipo: "Terceirizado",
        status: "Em atividade",
    },
    {
        nome: "Funcionário 8",
        cpf: "888.888.888-88",
        sexo: "Feminino",
        cargo: "Carpinteira",
        email: "funcionario8@example.com",
        telefone: "(88) 8888-8888",
        tipo: "Efetivo",
        dataContratacao: "2020-08-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 9",
        cpf: "999.999.999-99",
        sexo: "Masculino",
        cargo: "Servente",
        email: "funcionario9@example.com",
        telefone: "(99) 9999-9999",
        tipo: "Terceirizado",
        status: "Inativo",
    },
    {
        nome: "Funcionário 10",
        cpf: "000.000.000-00",
        sexo: "Feminino",
        cargo: "Técnica de Segurança",
        email: "funcionario10@example.com",
        telefone: "(00) 0000-0000",
        tipo: "Efetivo",
        dataContratacao: "2020-10-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 11",
        cpf: "111.111.111-12",
        sexo: "Masculino",
        cargo: "Engenheiro Civil",
        email: "funcionario11@example.com",
        telefone: "(11) 1111-1112",
        tipo: "Efetivo",
        dataContratacao: "2020-11-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 12",
        cpf: "222.222.222-23",
        sexo: "Feminino",
        cargo: "Arquiteta",
        email: "funcionario12@example.com",
        telefone: "(22) 2222-2223",
        tipo: "Efetivo",
        dataContratacao: "2020-12-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 13",
        cpf: "333.333.333-34",
        sexo: "Masculino",
        cargo: "Pedreiro",
        email: "funcionario13@example.com",
        telefone: "(33) 3333-3334",
        tipo: "Terceirizado",
        status: "Em atividade",
    },
    {
        nome: "Funcionário 14",
        cpf: "444.444.444-45",
        sexo: "Feminino",
        cargo: "Mestre de Obras",
        email: "funcionario14@example.com",
        telefone: "(44) 4444-4445",
        tipo: "Efetivo",
        dataContratacao: "2021-01-01",
        status: "Contratado",
    },
    {
        nome: "Funcionário 15",
        cpf: "555.555.555-56",
        sexo: "Masculino",
        cargo: "Eletricista",
        email: "funcionario15@example.com",
        telefone: "(55) 5555-5556",
        tipo: "Terceirizado",
        status: "Inativo",
    },
];

export default funcionarios;