name: Build and deploy Node.js app to Azure Web App - app-sgo-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd src/webapp  # Navega até o diretório do app React
          npm install
          npm run build --if-present

      - name: List files after build
        run: |
          cd src/webapp
          dir
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: src/webapp/build

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files after artifact download
        run: |
          dir

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Use o client-id da app registration
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Use o client secret da app registration
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Tenant ID do Azure

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-sgo-front'
          slot-name: 'Production'
          package: node-app.zip  # Verifique o caminho e o nome do arquivo
