name: Build and deploy Node.js app to Azure Web App - app-sgo-front

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write  # Necessário para o login no Azure
  contents: read   # Permissão padrão para ler o conteúdo do repositório

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd src/webapp  # Navega até o diretório do app React
          npm install
          npm run build --if-present

      - name: List files after build
        run: |
          cd src/webapp
          dir  # Use 'dir' em vez de 'ls' no Windows
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: src/webapp/build

  deploy:
    runs-on: windows-latest  # Altera para Windows para o deploy
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: List files after artifact download
        run: |
          dir  # Use 'dir' para listar os arquivos no Windows

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_75127E2E0A8E4CEAB54DF7DD53FC773D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB503D77CB6A403E9FB43F7C7BE8F652 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6D681E94FF4A4A9EBCABB486D9AB9B40 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-sgo-front'
          slot-name: 'Production'
          package: node-app.zip  # Certifique-se de que o nome do arquivo está correto
